### ISSUE TITLE
Error CS0534: 'MLXRCpuDepthFeature' does not implement inherited abstract member 'MLDepthFeature.Unproject(Vector2)'

### ISSUE THREAD

**Issue by maryam-fatima** [natmlx/NatML-ARFoundation#1]
I am trying to connect AR Foundation with my NatML edge prediction project where i am using a mobilenet-v2. When i updated the manifest.json file to include dependency

    "ai.natml.natml.arfoundation": "1.0.1"

following error appeared:
Library\PackageCache\ai.natml.natml.arfoundation@1.0.1\Runtime\Features\MLXRCpuDepthFeature.cs(22,25): error CS0534: 'MLXRCpuDepthFeature' does not implement inherited abstract member 'MLDepthFeature.Unproject(Vector2)'

I am using 
unity:2021.3.4f1
ai.natml.videokit: 0.0.12
arfoundation: 4.2.7

**Comment by olokobayusuf** [comment]
[Fixed in 1.0.2](https://github.com/natmlx/natml-arfoundation/releases/tag/1.0.2).
