### ISSUE TITLE
NatML AR conflicts with ARCore

### ISSUE THREAD

**Issue by Algit73** [natmlx/NatML-ARFoundation#2]
Hi,

I want to use the NatML ARFoundation aside ARCore and it seems there are some conflicts (about 200) between the Packages. I list some of them here:

1- GUID [300c4804f47d540fc9efec07999accf7] for asset 'Packages/com.unity.xr.arfoundation/Editor/ARSubsystems' conflicts with:
  'Packages/com.unity.xr.arsubsystems/Editor' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

2- GUID [3c6ef533f768476bac9249d73827adfe] for asset 'Packages/com.unity.xr.arfoundation/Editor/ARSubsystems/ARBuildProcessor.cs' conflicts with:
  'Packages/com.unity.xr.arsubsystems/Editor/ARBuildProcessor.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

3- Library\PackageCache\com.unity.xr.arfoundation@5.0.7\Runtime\ARFoundation\ARCameraManager.cs(173,16): error CS0246: The type or namespace name 'XRCameraBackgroundRenderingMode' could not be found (are you missing a using directive or an assembly reference?)

4- Library\PackageCache\com.unity.xr.arfoundation@5.0.7\Runtime\Simulation\Subsystems\PointCloud\SimulationPointCloudSubsystem.cs(20,33): error CS0115: 'SimulationPointCloudSubsystem.OnStart()': no suitable method found to override

I have set the configs as NatML ARFoundation requirements. Would you please provide an example project after all?

**Comment by olokobayusuf** [comment]
Hey @Algit73 what version of ARCore are you using? And can you share your project's `manifest.json` in the `Packages` folder?

**Comment by Algit73** [comment]
Sure.
ARCore: 4.2.9
Unity: 2022
ARFoundation: 5.0.7

Manifest:
{
  "scopedRegistries": [
    {
      "name": "NatML",
      "url": "https://registry.npmjs.com",
      "scopes": [
        "ai.natml",
        "ai.fxn"
      ]
    }
  ],
  "dependencies": {
    "ai.natml.natml.arfoundation": "1.0.3",
    "com.unity.collab-proxy": "1.17.7",
    "com.unity.feature.ar": "1.0.0",
    "com.unity.feature.development": "1.0.1",
    "com.unity.ide.rider": "3.0.16",
    "com.unity.ide.visualstudio": "2.0.22",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.learn.iet-framework": "3.1.1",
    "com.unity.test-framework": "1.1.33",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.7.2",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.7.8",
    "com.unity.xr.arcore": "4.2.9",
    "com.unity.xr.management": "4.2.1",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }

**Comment by olokobayusuf** [comment]
Can you try upgrading your ARCore dependency to 5.x? This isn't a NatML bug, so I'm closing the issue.
